# Generated by Django 3.2.8 on 2021-10-28 15:03

import dcim.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0051_asn_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='asn',
            field=dcim.fields.ASNField(blank=True, null=True, unique=True),
        ),
    ]
