# Generated by Django 3.2.11 on 2022-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0055_servicetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhrpgroupassignment',
            name='interface_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='assigned_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
