# Generated by Django 3.2.12 on 2022-04-19 12:37

import django.contrib.postgres.fields
from django.db import migrations
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_standardize_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allowed_ips',
            field=django.contrib.postgres.fields.ArrayField(base_field=ipam.fields.IPNetworkField(), blank=True, null=True, size=None),
        ),
    ]
