# Generated by Django 4.2.6 on 2023-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_created_auto_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
