# Generated by Django 3.2.11 on 2022-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0032_provider_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuittermination',
            name='_link_peer_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
