# Generated by Django 3.2.8 on 2021-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0135_location_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='airflow',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
