# Generated by Django 3.2.8 on 2021-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0136_device_airflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('site', 'parent', 'name'), ('site', 'parent', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('parent', 'slug'), ('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sitegroup',
            unique_together={('parent', 'slug'), ('parent', 'name')},
        ),
    ]
