# Generated by Django 3.2.8 on 2021-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0136_wireless'),
        ('wireless', '0001_wireless'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='wireless_lans',
            field=models.ManyToManyField(blank=True, related_name='interfaces', to='wireless.WirelessLAN'),
        ),
    ]
