# Generated by Django 3.2.8 on 2021-10-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0137_relax_uniqueness_constraints'),
        ('ipam', '0051_asn_model')
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='asn',
        ),
    ]
