# Generated by Django 4.0.4 on 2022-04-25 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='termination_a_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='cable',
            name='termination_b_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), null=True, size=None),
        ),
    ]
