# Generated by Django 4.0.4 on 2022-04-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0155_cable_copy_termination_ids'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cable',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cable',
            name='termination_a_id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='termination_b_id',
        ),
    ]
