# Generated by Django 4.0.4 on 2022-04-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0155_populate_cable_terminations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cable',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterUniqueTogether(
            name='cable',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cable',
            name='termination_a_id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='termination_a_type',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='termination_b_id',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='termination_b_type',
        ),
    ]
