# Generated by Django 4.0.4 on 2022-05-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0158_cablepath_populate_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cablepath',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cablepath',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='cablepath',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='cablepath',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='cablepath',
            name='origin_type',
        ),
    ]
