# Generated by Django 4.1.5 on 2023-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetemplate',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
