# Generated by Django 4.2.5 on 2023-12-05 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0181_rename_device_role_device_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='starting_unit',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
