# Generated by Django 3.2b1 on 2021-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0058_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttemplate',
            name='as_attachment',
            field=models.BooleanField(default=True),
        ),
    ]
