# Generated by Django 3.2.11 on 2022-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0070_customlink_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageattachment',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='assigned_object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='changed_object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='related_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
