# Generated by Django 4.0.4 on 2022-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0074_customfield_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='ui_visibility',
            field=models.CharField(default='read-write', max_length=50),
        ),
    ]
