# Generated by Django 4.1.1 on 2022-10-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0078_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobresult',
            options={'ordering': ['-created']},
        ),
    ]
