# Generated by Django 4.1.1 on 2022-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0079_change_jobresult_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
