# Generated by Django 4.1.6 on 2023-02-07 08:21

from django.db import migrations
import extras.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0084_staging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedvalue',
            name='value',
            field=extras.fields.CachedValueField(),
        ),
    ]
