# Generated by Django 4.2.2 on 2023-06-14 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0093_configrevision_ordering'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taggeditem',
            new_name='extras_tagg_content_717743_idx',
            old_fields=('content_type', 'object_id'),
        ),
    ]
