# Generated by Django 4.2.6 on 2023-10-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedvalue',
            options={'ordering': ('weight', 'object_type', 'value', 'object_id')},
        ),
    ]
