# Generated by Django 3.2.11 on 2022-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_extend_tag_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactassignment',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
