name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@feat-rockcraft-from-src
    secrets: inherit
    with:
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.1/stable
      channel: 1.28-strict/stable
      tmate-debug: true
