name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: ./charm/localstack-installation.sh
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.1/stable
      channel: 1.28-strict/stable
      rockcraft-repository: javierdelapuente/rockcraft
      rockcraft-ref: django-extension-install-app-merge
      charmcraft-repository: weiiwang01/charmcraft
      charmcraft-ref: feat-12f-django
      charm-directory: "charm"
