name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: ./charm/localstack-installation.sh
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.5/stable
      channel: 1.31-strict/stable
      rockcraft-channel: latest/edge
      charmcraft-channel: latest/edge
      charm-directory: "charm"
      tmate-debug: true
      tmate-timeout: 30
