name: Publish to edge

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@test-netbox
    secrets: inherit
    with:
      channel: latest/edge
      docs-working-directory: "./charm"
      charm-working-directory: "./charm"

