name: Tests with spread

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  run-spread-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spread_job: ['github-ci:ubuntu-22.04-amd64:tests/spread/', 'github-ci:ubuntu-22.04-amd64:tests/spread/scenario/']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: 'stable'

      - name: Install spread
        run: |
          go install github.com/snapcore/spread/cmd/spread@latest
      - name: Run tests
        run: |
          sudo adduser --gecos "" --disabled-password ubuntu
          echo "ubuntu:ubuntu" | sudo chpasswd
          spread ${{ matrix.spread_job }}
      - name: Tmate debugging session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
