name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    uses: javierdelapuente/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      shellcheck-working-directory: "./charm"
      docs-working-directory: "./charm"
